version: "3.9"

services:
  server1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server

    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 5s
      timeout: 2s
      retries: 3




